name = "line-crm-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "e8193463b99b767e99c0b65cf6da3681"

# API_KEY is set via `wrangler secret put API_KEY`
# Do NOT hardcode secrets here

[vars]
WORKER_URL = "https://line-crm-worker.daigo-tashiro.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "afa619c3-26d0-43c1-97c2-631c7e22653e"

[triggers]
crons = ["*/5 * * * *"]
